// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "SwiftTestHarness",
    dependencies: [
        .package(name: "PkgConfig", path: "../build/SPMPackage/macosArm64/Debug")
    ],
    targets: [
        .testTarget(
            name: "SwiftTestHarnessTests",
            dependencies: [
                .product(name: "PkgConfigLibrary", package: "PkgConfig")
            ],
            linkerSettings: [
                // The SPM package generated by Kotlin's embedSwiftExportForXcode
                // task contains Swift wrapper sources and C bridge declarations,
                // but the actual symbol implementations
                // (`__root____getExceptionMessage__...`) live in
                // `libPkgConfig.a` produced by the
                // `linkSwiftExportBinaryDebugStaticMacosArm64` /
                // `mergeMacosDebugSwiftExportLibraries` chain. Xcode wires
                // that archive into its own link step via
                // BUILT_PRODUCTS_DIR; a standalone `swift test` invocation
                // has to point at it explicitly. The archive lands at
                // `<repo>/build/swift-test/libPkgConfig.a` when the
                // embed task runs with the macOS Xcode-style environment
                // variables (see .github/workflows/swift.yml).
                .unsafeFlags([
                    "-L", "../build/swift-test",
                    "-lPkgConfig",
                ]),
                // The Kotlin/Native runtime baked into `libPkgConfig.a`
                // references CoreFoundation (`_CFAttributedString*`) and
                // Darwin XPC (`_xpc_session_*`) symbols. Xcode auto-links
                // these via the SDK's implicit framework list when
                // consuming an SPM package through a project; standalone
                // `swift test` does not, so the link fails with
                // `Undefined symbols for architecture arm64`. Link both
                // frameworks explicitly so `swift test` resolves the same
                // platform surface Xcode picks up automatically.
                .linkedFramework("CoreFoundation"),
                .linkedFramework("Foundation"),
            ]
        ),
    ]
)
